### ISSUE TITLE
0.2.11 failed to start

### ISSUE THREAD

**Issue by karl-johan-grahn** [martinlindhe/wmi_exporter#169]
When installing the latest release https://github.com/martinlindhe/wmi_exporter/releases/download/v0.2.11/wmi_exporter-0.2.11-amd64.msi I get this error:
![image](https://user-images.githubusercontent.com/6355577/37391678-2de4c62c-276c-11e8-8b3d-80d1526bc8a1.png)

**Comment by martinlindhe** [comment]
Can confirm issue. In the meantime you could use 0.2.10, there should be no functional changes.

**Comment by martinlindhe** [comment]
Quick update:

- wmi_exporter.exe is correctly built.

- event viewer logs the following:
    - A timeout was reached (30000 milliseconds) while waiting for the WMI exporter service to connect.
    - The WMI exporter service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion.

Currently investigating wix things.

**Comment by carlpett** [comment]
I'm away on a business trip so limited ability to assist, but some thoughts to investigate:
- Does it work if launched "manually" from the command line? 
- Any interesting vendor changes in the WBEM libs?

**Comment by martinlindhe** [comment]
@carlpett Hey, I was just about to reach out to you! :-)

wmi_exporter.exe runs correctly if launched directly.
I thought at first the issue was the dep bump yesterday, but I have now rebuilt the .msi on older commits with the same result.

Example:

    git checkout b9b8cfd1ca08892a16a37cfab22931b0e134db38   # the commit for tag v0.2.10
    .\installer\build.ps1 -PathToExecutable .\wmi_exporter.exe -Version "0.999.999" -Arch "amd64"

the resulting .msi fails the same. So I think we can rule out the dep bump.

In order to get anywhere I had to update build.ps1 due to https://blog.github.com/2018-02-23-weak-cryptographic-standards-removed/, commit https://github.com/martinlindhe/wmi_exporter/commit/191debeed6b34eb595f1c2ca234536ceee5e00e8

**Comment by martinlindhe** [comment]
More details:

the wix-binaries.zip sha256 is confirmed to be unchanged.
My local download has hash da034c489bd1dd6d8e1623675bf5e899f32d74d6d8312f8dd125a084543193de, which can also be found in https://github.com/golang/build/blob/master/cmd/release/releaselet.go#L298

**Comment by martinlindhe** [comment]
Actually I misread. We use wix 3.11 from june 2017. There is a wix 3.11.1 from Nov 2017. I am trying that one now.

**Comment by martinlindhe** [comment]
Same issue with wix 3.11.1. however, we should upgrade to it as soon as this is resolved due to security issue fixed: https://www.firegiant.com/blog/2017/12/31/wix-v3.10.4-and-wix-v3.11.1-released/

**Comment by martinlindhe** [comment]
Been diff:ing msi install logs without much success. This log format is really not designed to be consumed by anyone...

**Comment by martinlindhe** [comment]
I updated the v0.2.11 release with details. https://github.com/martinlindhe/wmi_exporter/releases/tag/v0.2.11

I'm out of time today to dig deeper.

@hairyhenderson, did you experience similar issues?

**Comment by hairyhenderson** [comment]
@martinlindhe I didn't... But I didn't get the chance to test it very deeply yet. @karl-johan-grahn is a colleague of mine, so I'll work with him to see if we can figure it out.

The main change I was looking for with the dep updates is for the `github.com/prometheus/client_golang` packages (some updated naming with some of the metrics). So maybe a temporary workaround would be to revert the dep updates and _only_ update the one package.

I'll dig into this further and report back.

**Comment by carlpett** [comment]
Still not in a position to actually try stuff, but I _can_ look at diffs :) I noticed that we also updated the vendoring for `golang.org/x/sys/windows/svc`. Among other things, the update contained [this commit](https://github.com/golang/sys/commit/e62c3de784db939836898e5c19ffd41bece347da), which seems to change how Go works with the Windows API calls to run as a service. 
It might be interesting to try to revert this vendor update and see if that helps.

**Comment by martinlindhe** [comment]
@carlpett Thanks for having a look!

I did believe I ruled this out, but I find it more likely I messed something up.
I'll have a look again tomorrow or so, hopefully. In the meantime I managed to remove the v0.2.11 release from the Releases page, so hopefully not so many users should be affected.

**Comment by karl-johan-grahn** [comment]
Yes, we noticed that ;-) By the way, the failure we had with 0.2.11 was related to the MSI - is the exe of 0.2.11 OK?

**Comment by martinlindhe** [comment]
@karl-johan-grahn Yes, I believe the exe is okay. It ran as expected from my limited testing.
But @carlpett pointed out things that makes me question my conclusions from the other day a bit, so maybe take it with a grain of salt.

**Comment by carlpett** [comment]
Right, I'm finally home and able to test. On my machine, replacing the vendor directory with the one from 0.2.10 works. Trying some surgical replacement is a bit harder, since other vendoring upgrades (logrus) seem to have pulled in stuff from golang.org. I'll see if I can do it with some more precision, to isolate the issue, but I think it is safe to assume that this is vendoring-related, at least.

**Comment by martinlindhe** [comment]
@carlpett thanks for taking your time to have a look! This is great news, means we should be able to resolve it by pinning dependencies.

**Comment by carlpett** [comment]
After some binary search, the culprit appears to be the prometheus vendoring.
I haven't confirmed it yet, but my current theory is that it is because we changed the flags library in common/log quite some time ago, and this in turn means that we no longer get the automatically added flags for logging in wmi_exporter, which in turn means that wmi_exporter will immediately quit because of the unknown flag for logging to the event log, that we set...

**Comment by carlpett** [comment]
Yes, the unknown flag is what is going wrong. So, we should just fix this. Perhaps it is time to merge #112...

**Comment by carlpett** [comment]
Also, this implies handling #114 as well

**Comment by martinlindhe** [comment]
Okay, cool. So would #112 and #114 be required to solve to sort this in one sweep, or can we do it in smaller steps?

Also, changing the flags implies we bump minor version (eg 0.2.x -> 0.3.x) because of backward compatibility breakage.

**Comment by martinlindhe** [comment]
(Also, sorry for not having time for assisting more. With some luck, I may have a upcoming gig that may change this for the better).

**Comment by poblahblahblah** [comment]
I think this should be good to close out and just skip 0.2.11.

**Comment by carlpett** [comment]
This was fixed by #112. New release upcoming
